name: Form 1
stages:
  start:
    about: First stage
    items:
      - name: name
        info: Name of product.
        type: shorttext
      - name: info
        info: Product information.
        type: shorttext
      - name: metameta
        info: this could include some meta info
        type: longtext
    on_submit: actionOnStartSubmit
    on_generate: actionOnStartGenerate
  second:
    about: Second stage
    items:
      - name: test2
        type: shorttext
exec_hint: [start, second]
on_load: actionOnLoadForm
