name = "test"
slug = "test"
type = "app"
env = ".env"

[objects.maindb]
type = "dyndb"
data = { migration_type = "json.v1", migration_file = "migration.json" }

[objects.mainagent]
type = "agent"


test = "www/test.html"

[files]
www = "../assets"


# Steps below

[[steps]]
name = "doxyz"
[steps.data]
mnop = "pqr"


[[steps]]


