project_name: temphia
env:
  - GO111MODULE=on
builds:

- id: temphia-darwin-amd64
  env:
    - CGO_ENABLED=1
    - CC=o64-clang
    - CXX=o64-clang++
  main: ./main.go
  goos:
    - darwin
  goarch:
    - amd64

- id: temphia-darwin-arm64
  env:
    - CGO_ENABLED=1
    - CC=aarch64-apple-darwin21.4-clang
    - CXX=aarch64-apple-darwin21.4-clang++
  main: ./main.go
  goos:
    - darwin
  goarch:
    - arm64

- id: temphia-linux
  env:
    - CGO_ENABLED=1
  main: ./main.go
  goos:
    - linux
  goarch:
    - amd64

- id: temphia-linux-arm64
  env:
    - CGO_ENABLED=1
    - CC=aarch64-linux-gnu-gcc
  main: ./main.go
  goos:
    - linux
  goarch:
    - arm64

- id: temphia-windows
  ldflags: -buildmode=exe
  env:
    - CGO_ENABLED=1
    - CC=x86_64-w64-mingw32-gcc
    - CXX=x86_64-w64-mingw32-g++
  main: ./main.go
  goos:
    - windows
  goarch:
    - amd64

archives:
- format: binary