name: simplestatic
slug: simplestatic
objects:
  # room1:
  #   name: Broacast Channel
  #   type: resource
  # maindb:
  #   name: Main Database
  #   type: datagroup
  # startup:
  #   type: target_hook
  #   name: Startup Hook
  mainapp:
    type: agent
steps:
  - name: add_main_agent
    type: add_agent
    data: {
      "name": "default"
      "type": "static"
      "web_files": {
        "index.html": "-"
      }
    }