on: [workflow_dispatch]

# act workflow_dispatch -W .github/workflows/build_binaries.yml

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: run releaser
        run: make snapshot

      #artifacts
      - name: save temphia_windows_amd64
        uses: actions/upload-artifact@v3
        with:
          name: temphia_windows_amd64
          path: dist/temphia-windows_windows_amd64_v1/
      - name: save temphia_linux_amd64
        uses: actions/upload-artifact@v3
        with:
          name: temphia_linux_amd64
          path: dist/temphia-linux_linux_amd64_v1/
      - name: save temphia_linux_arm64
        uses: actions/upload-artifact@v3
        with:
          name: temphia_linux_arm64
          path: dist/temphia-linux-arm64_linux_arm64/
      - name: save temphia_darwin_amd64
        uses: actions/upload-artifact@v3
        with:
          name: temphia_darwin_amd64
          path: dist/temphia-darwin-amd64_darwin_amd64_v1/
      - name: save temphia_darwin_arm64
        uses: actions/upload-artifact@v3
        with:
          name: temphia_darwin_arm64
          path: dist/temphia-darwin-arm64_darwin_arm64/
