name: build_binaries

on: [push]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      
      - name: run releaser
        run: make snapshot

      #artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: temphia_windows_amd64
          path: dist/temphia-windows_windows_amd64_v1/
      - uses: actions/upload-artifact@v3
        with:
          name: temphia_linux_amd64
          path: dist/temphia-linux_linux_amd64_v1/
      - uses: actions/upload-artifact@v3
        with:
          name: temphia_darwin_amd64
          path: dist/temphia-darwin-amd64_darwin_amd64_v1/
      - uses: actions/upload-artifact@v3
        with:
          name: temphia_darwin_arm64
          path: dist/temphia-darwin-arm64_darwin_arm64/